<?php echo $this->partial('partials/header.phtml', array('acl' => $this->acl, 't' => $this->t)); ?>
<h3><?php echo $this->t->_('Update'); ?></h3>
<p><?php echo $this->t->_('Download the following file'); ?>:</p>
<pre>http://download.seinternal.com/integration/installers/plesk-windows/installer.bat</pre>
<p><?php echo $this->t->_('From the command line run the following command'); ?>:</p>
<pre>cmd /k installer.bat</pre>
